FROM arm64v8/ubuntu

RUN dpkg --add-architecture arm64
RUN apt update 
RUN apt install curl -y
RUN apt install certbot -y
# RUN mkdir /etc/letsencrypt

CMD ["/entrypoint.sh"]

COPY secret-patch-template.json /
COPY deployment-patch-template.json /
COPY entrypoint.sh /
