FROM arm64v8/ubuntu

RUN apt update && apt install certbot:arm64 -y
# RUN mkdir /etc/letsencrypt

CMD ["/entrypoint.sh"]

COPY secret-patch-template.json /
COPY deployment-patch-template.json /
COPY entrypoint.sh /
